
bases:
  - ../../bases/argocd

resources:
  - applications/kudo.yaml
  - applications/nginx.yaml
  - cluster-secrets/kudo.yaml
  - cluster-secrets/nginx.yaml

namespace: argocd

#patchesStrategicMerge:
  #- patch-argocd-server.yaml

configMapGenerator:
  - name: argocd-cm
    # behavior: merge
    behavior: replace
    files:
      - repositories=repositories/github-sheldonirwin.yaml

secretGenerator:
  - name: github-sheldonirwin
    files:
      - sshPrivateKey=key/id_rsa_argocd

generatorOptions:
  disableNameSuffixHash: true
