apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/sheldonirwin/gitops-demo.git
    targetRevision: HEAD
    path: overlays/nginx

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx

  # Sync policy
  syncPolicy:
    automated: {}
  #  automated:
  #    prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
  #    selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
  #  validate: true # Validate resources before applying to k8s, defaults to true.

