apiVersion: v1
kind: Secret
metadata:
  name: nginx-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: nginx.co
  server: https://svc.kubernetes
  config: |
    {
      "username": nginx",
      "password": nginx",
      "tlsClientConfig": {
        "insecure": false
      }
    }




