apiVersion: v1
kind: Secret
metadata:
  name: kudo-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: kudo.co
  # server: https://192.168.39.77:8443 #https://kudo.co:8443
  server: https://kudo.co:8443
  config: |
    {
      "username": "kudo",
      "password": "kudo",
      "tlsClientConfig": {
        "insecure": false
      }
    }