apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Avoid overriding names / namespace here. Conflicts with cert-manager's base yaml.

namespace: argocd

resources:
  - namespace.yaml
  - argocd.yaml
  - ingress.yaml
